name: pyross
channels:
  - conda-forge
dependencies:
  - python
  - cython
  - numpy
  - matplotlib
  - jupyter
  - scipy
  - pytest 
  - pytest-cov
  - pandas
  - sympy
  - ipython
  - nbconvert
  - xlrd
  - pip
  - pip:
    - cma
    - dill
    - nlopt
    - pathos
    - git+https://github.com/kbarbary/nestle.git
