name: pyross
dependencies:
  - python
  - conda-forge::cython
  - conda-forge::numpy
  - conda-forge::matplotlib
  - conda-forge::scipy 
  - conda-forge::pandas 
  - conda-forge::xlrd 
  - conda-forge::nlopt
  - cma-es::cma 
  - conda-forge::pathos
