name: pyross
channels:
  - conda-forge
dependencies:
  - python
  - cython
  - numpy
  - matplotlib
  - jupyter
  - scipy
  - pytest 
  - pytest-cov
  - pandas
  - sympy
  - ipython
  - nbconvert
  - xlrd
  - dynesty
  - emcee
  - nlopt
  - pip
  - pip:
    - cma
    - dill
    - pathos
