name: pyross
channels:
  - conda-forge
dependencies:
  - python
  - cython
  - dill
  - numpy
  - matplotlib
  - jupyter
  - scipy
  - nlopt=2.6.2
  - pathos
  - pip
  - pytest 
  - pytest-cov
  - pandas
  - sympy
  - ipython
  - nbconvert
  - xlrd
  - pip:
    - cma
    - git+https://github.com/kbarbary/nestle.git
