name: build

on: [push, pull_request]

jobs:

  build-and-test:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest","windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
         python-version: 3.7 
         architecture: x64

      - name: make-pyross
        shell: bash -l {0}
        run: |
          make

      - name: test-pyross
        shell: bash -l {0}
        run: |
          make test


