name: CI

on: [push, pull_request]

jobs:

  build-and-test:
    name: install
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies 
        run: python -m pip install -r requirements.txt
      
      - name: Install pyross 
        run: python setup.py install 

      - name: Test pyross
        run: cd tests && python quick_test.py


