name: Notebooks

on:
    schedule:
      # 4am daily
      - cron:  '0 4 1-29/3 * *'

jobs:

  build-and-test:
    name: notebooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pyross
         environment-file: environment.yml
         # auto-activate-base: true
      - name: make-pyross
        shell: bash -l {0}
        run: |
          conda activate pyross
          make
          # make nbtest
      - name: testing-deterministic
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/deterministic"  recursive=False
      - name: testing-stochastic
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/stochastic"  recursive=False
      - name: testing-hybrid
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/hybrid"  recursive=False
      - name: testing-contactMatrix
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/contactMatrix"  recursive=False
      - name: testing-control
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/control/nbtests"  recursive=False
      - name: end
        shell: bash -l {0}
        run: |
          echo "skipped inference and forcast"
    

                # make nbtest
