name: Notebooks

on: [push, pull_request]
#on:
#    schedule:
#      # 4am daily
#      - cron:  '0 1 * * *'

jobs:

  build-and-test:
    name: check examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies 
        run: python -m pip install -r requirements.txt
      
      - name: Install pyross 
        run: python setup.py install 

      - name: testing-inference
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/inference" recursive=False
      - name: testing-deterministic
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/deterministic"  recursive=False
      - name: testing-stochastic
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/stochastic"  recursive=False
      - name: testing-control
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/control"  recursive=False
      - name: testing-forecast
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/forecast/" recursive=False
